### ISSUE TITLE
Address fetch+cancel

### ISSUE THREAD

**Issue by tgvashworth** [tgvashworth/fetch-engine#2]
The [fetch spec](https://github.com/whatwg/fetch) doesn't have `cancel`, because Promises/A+ doesn't have `cancel`, and there hasn't been a resolution in whatwg/fetch#27. So, a correctly implemented timeout/deadline plugin is tricky because the [fetch polyfill](https://github.com/github/fetch) — which this would likely rely on, probably via [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) — doesn't have `cancel`.

Importantly, it's not good enough to just reject the Promise; the whole point is that the network request is taking a long time and we want to close it to [allow other connections to open](http://stackoverflow.com/a/985704).

Options are:
- define a cancel operation on the fetch promise. _Opinion: yuck._
- define a cancel operation on the Request. _Opinion: [also yuck](https://github.com/whatwg/fetch/issues/20#issuecomment-74236024)._
- come up with something new, potentially feeding it back into the above specs

**Comment by phuu** [comment]
The API as discussed in #1 describes a `{ promise, cancel }` tuple, which is think is a good compromise for now: if Promises become cancellable, that'll work, otherwise `cancel` will.

The next concern is: do any of the fetch libraries expose enough API that you *can* cancel?

**Comment by phuu** [comment]
Wrote a [blog post](https://phuu.net/2015/11/25/promise-and-fetch.html) about this.

**Comment by phuu** [comment]
De-prioritised for 1.0.0 milestone — we can revisit.

**Comment by tgvashworth** [comment]
They [did it](https://fetch.spec.whatwg.org/#abort-fetch).

Will open another issue for hooking this us.
